config/routes.rb
M3fe::Application.routes.draw do
  namespace :public do
    resources :home, only: :index
    resources :job_wanted_ads, only: [:index, :show, :create] 
    resources :job_offered_ads, only: [:index, :show, :create]
  end

  namespace :users do
    resources :job_wanted_ads
    resources :job_offered_ads
  end

  root :to => 'public/home#index'
end

app/models/ad.rb
class Ad < ActiveRecord::Base
  attr_accessible :body, :phone, :title

  belongs_to :advertisable, polymorphic: true

  validates :body, :title, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :code, :locale_index

  belongs_to :categorizable, polymorphic: true
end

app/models/job_offered_ad.rb
class JobOfferedAd < ActiveRecord::Base
  include AdExtensions
  ad include: :work_place

  attr_accessible :pay, :work_place

  belongs_to :user
  has_one :base_ad, as: :advertisable, class_name: Ad
  has_one :category, as: :categorizable

  delegate :body, :phone, :title, to: :base_ad

  accepts_nested_attributes_for :base_ad

  validates_associated :base_ad
end

app/models/job_wanted_ad.rb
class JobWantedAd < ActiveRecord::Base
  include AdExtensions
  ad include: :desired_location

  attr_accessible :attachment, :desired_location, :phone, :body, :title

  belongs_to :user
  has_one :base_ad, as: :advertisable, class_name: Ad
  has_one :category, as: :categorizable

  delegate :body, :phone, :title, to: :base_ad

  accepts_nested_attributes_for :base_ad

  validates_associated :base_ad

  mount_uploader :attachment, AttachmentUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :default_locale, :email, :name

  has_many :job_offered_ads
  has_many :job_wanted_ads

  validates :email, :name, presence: true
  validates :email, format: { with: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i }

  after_save :set_checksum_id

  def checksum_id=(cid)
    raise "read only attribute"
  end

  def ==(other)
    return unless other.try { |o| o.respond_to :checksum_id }
    this.checksum_id == other.checksum_id
  end

  protected
  def set_checksum_id
    return if checksum_id
    require 'digest'
    write_attribute(:checksum_id, Digest::SHA256.new.hexdigest(email + created_at.to_s))
    save!
    raise "could not set checksum_id" if !self.checksum_id
  end
end

app/models/user_ability.rb
class UserAbility
  include CanCan::Ability

  def initialize(user)
    guest_permissions
    user_permissions(user) if user.persisted?
  end

  def guest_permissions
    can :read, [JobOfferedAd, JobWantedAd]
  end

  def user_permissions(u)
    can :manage, [JobOfferedAd, JobWantedAd], user: { hash_id: u.hash_id }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :current_user
  before_filter :require_login, only: [:update, :destroy]

  def current_ability
    @current_ability ||= UserAbility.new(@current_user)
  end

  def current_user
    @current_user ||= User.new(params[:user])
    @current_user.save! if @current_user.valid? and @current_user.new_record?
  end

  protected

  def require_login
    unless current_user.persisted?
      render nothing: true, status: 401
    end
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/controllers/users/job_offered_ads_controller.rb
class Users::JobOfferedAdsController < UsersController
  respond_to :json, :js

  def update
    ad = JobOfferedAd.find params[:id]
    respond_to do |r|
      if ad.update_attributes(params[:ad])
        r.json { render json: ad }
      else
        r.json { render json: ad.errors, status: 500 }
      end
    end
  end

  def destroy
    ad = JobOfferedAd.find params[:id]
    respond_to do |r|
      if ad.try :destroy
        r.json { render json: ad }
      else
        r.json { render json: ad, status: 500 }
      end
    end
  end
end

app/controllers/users/job_wanted_ads_controller.rb
class Users::JobWantedAdsController < UsersController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_controller_helper.rb
module HomeControllerHelper
end

app/helpers/job_offered_ads_helper.rb
module JobOfferedAdsHelper
end

app/helpers/job_wanted_ads_helper.rb
module JobWantedAdsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/job_offered_ads/_form.html.erb
<%= form_for(@job_offered_ad) do |f| %>
  <% if @job_offered_ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_offered_ad.errors.count, "error") %> prohibited this job_offered_ad from being saved:</h2>

      <ul>
      <% @job_offered_ad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :work_place %><br />
    <%= f.text_field :work_place %>
  </div>
  <div class="field">
    <%= f.label :pay %><br />
    <%= f.number_field :pay %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_offered_ads/edit.html.erb
<h1>Editing job_offered_ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_offered_ad %> |
<%= link_to 'Back', job_offered_ads_path %>

app/views/job_offered_ads/index.html.erb
<h1>Listing job_offered_ads</h1>

<table>
  <tr>
    <th>User</th>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Work place</th>
    <th>Pay</th>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @job_offered_ads.each do |job_offered_ad| %>
  <tr>
    <td><%= job_offered_ad.user %></td>
    <td><%= job_offered_ad.name %></td>
    <td><%= job_offered_ad.email %></td>
    <td><%= job_offered_ad.phone %></td>
    <td><%= job_offered_ad.work_place %></td>
    <td><%= job_offered_ad.pay %></td>
    <td><%= job_offered_ad.title %></td>
    <td><%= job_offered_ad.body %></td>
    <td><%= link_to 'Show', job_offered_ad %></td>
    <td><%= link_to 'Edit', edit_job_offered_ad_path(job_offered_ad) %></td>
    <td><%= link_to 'Destroy', job_offered_ad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job offered ad', new_job_offered_ad_path %>

app/views/job_offered_ads/new.html.erb
<h1>New job_offered_ad</h1>

<%= render 'form' %>

<%= link_to 'Back', job_offered_ads_path %>

app/views/job_offered_ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @job_offered_ad.user %>
</p>

<p>
  <b>Name:</b>
  <%= @job_offered_ad.name %>
</p>

<p>
  <b>Email:</b>
  <%= @job_offered_ad.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @job_offered_ad.phone %>
</p>

<p>
  <b>Work place:</b>
  <%= @job_offered_ad.work_place %>
</p>

<p>
  <b>Pay:</b>
  <%= @job_offered_ad.pay %>
</p>

<p>
  <b>Title:</b>
  <%= @job_offered_ad.title %>
</p>

<p>
  <b>Body:</b>
  <%= @job_offered_ad.body %>
</p>


<%= link_to 'Edit', edit_job_offered_ad_path(@job_offered_ad) %> |
<%= link_to 'Back', job_offered_ads_path %>

app/views/job_wanted_ads/_form.html.erb
<%= form_for(@job_wanted_ad) do |f| %>
  <% if @job_wanted_ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_wanted_ad.errors.count, "error") %> prohibited this job_wanted_ad from being saved:</h2>

      <ul>
      <% @job_wanted_ad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :desired_location %><br />
    <%= f.text_field :desired_location %>
  </div>
  <div class="field">
    <%= f.label :attachments %><br />
    <%= f.text_field :attachments %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_wanted_ads/edit.html.erb
<h1>Editing job_wanted_ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_wanted_ad %> |
<%= link_to 'Back', job_wanted_ads_path %>

app/views/job_wanted_ads/index.html.erb
<h1>Listing job_wanted_ads</h1>

<table>
  <tr>
    <th>User</th>
    <th>Phone</th>
    <th>Desired location</th>
    <th>Attachments</th>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @job_wanted_ads.each do |job_wanted_ad| %>
  <tr>
    <td><%= job_wanted_ad.user %></td>
    <td><%= job_wanted_ad.phone %></td>
    <td><%= job_wanted_ad.desired_location %></td>
    <td><%= job_wanted_ad.attachments %></td>
    <td><%= job_wanted_ad.title %></td>
    <td><%= job_wanted_ad.body %></td>
    <td><%= link_to 'Show', job_wanted_ad %></td>
    <td><%= link_to 'Edit', edit_job_wanted_ad_path(job_wanted_ad) %></td>
    <td><%= link_to 'Destroy', job_wanted_ad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job wanted ad', new_job_wanted_ad_path %>

app/views/job_wanted_ads/new.html.erb
<h1>New job_wanted_ad</h1>

<%= render 'form' %>

<%= link_to 'Back', job_wanted_ads_path %>

app/views/job_wanted_ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @job_wanted_ad.user %>
</p>

<p>
  <b>Phone:</b>
  <%= @job_wanted_ad.phone %>
</p>

<p>
  <b>Desired location:</b>
  <%= @job_wanted_ad.desired_location %>
</p>

<p>
  <b>Attachments:</b>
  <%= @job_wanted_ad.attachments %>
</p>

<p>
  <b>Title:</b>
  <%= @job_wanted_ad.title %>
</p>

<p>
  <b>Body:</b>
  <%= @job_wanted_ad.body %>
</p>


<%= link_to 'Edit', edit_job_wanted_ad_path(@job_wanted_ad) %> |
<%= link_to 'Back', job_wanted_ads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t("app.title") %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "shared/header" %>
<div id="m3fe-app">
  <%= yield %>
</div>
<%= render partial: "shared/footer" %>
</body>
</html>

app/views/shared/_footer.html.erb
<footer>Footer</footer>

app/views/shared/_header.html.erb
<header>Ruishi Gongzuo Mami</header>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :hash_id %><br />
    <%= f.text_field :hash_id %>
  </div>
  <div class="field">
    <%= f.label :default_locale %><br />
    <%= f.text_field :default_locale %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Hash</th>
    <th>Default locale</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.hash_id %></td>
    <td><%= user.default_locale %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Hash:</b>
  <%= @user.hash_id %>
</p>

<p>
  <b>Default locale:</b>
  <%= @user.default_locale %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>